[build-system]
build-backend = "hatchling.build"
requires = ["hatchling", "hatch-build-scripts"]
##############################
# >>> Hatch Build Config <<< #
##############################

[project]
name = "reactpy-apexcharts"
description = "ApexCharts components for ReactPy"
readme = "README.md"
keywords = ["React", "ReactJS", "ReactPy", "ApexCharts", "charts", "components"]
license = "MIT"
authors = [{ name = "Steve Jones", email = "jonesst2608@gmail.com" }]
requires-python = ">=3.9"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = ["reactpy==2.0.0b7"]
dynamic = ["version"]
urls.Homepage = "https://github.com/stevej2608/reactpy-apexcharts"
urls.Source = "https://github.com/stevej2608/reactpy-apexcharts"

[tool.hatch.version]
path = "src/reactpy_apexcharts/__init__.py"

[tool.hatch.build.targets.sdist]
include = ["/src", "/tests", "/examples", "/utils"]
artifacts = ["/src/reactpy_apexcharts/static/"]
[tool.hatch.build.targets.wheel]
packages = ["src/reactpy_apexcharts"]
artifacts = ["/src/reactpy_apexcharts/static/"]
[tool.hatch.metadata]
license-files = { paths = ["LICENSE"] }

[tool.hatch.envs.default]
installer = "uv"

[[tool.hatch.build.hooks.build-scripts.scripts]]
commands = [
  "bun install --cwd src/js",
  'bun build src/js/src/index.tsx --outdir src/reactpy_apexcharts/static --entry-naming bundle.js --target=browser --format=esm --minify --root=.',
]
artifacts = []

#############################
# >>> Hatch Test Runner <<< #
#############################

[tool.hatch.envs.hatch-test]
extra-dependencies = [
  "asgi_tools",
  "asgiref",
  "exceptiongroup",
  "jsonpointer",
  "orjson",
  "pillow",
  "pixelmatch",
  "playwright",
  "pydantic",
  "pyright",
  "pytest-asyncio",
  "pytest-sugar",
  "responses",
  "servestatic",
  "starlette",
  "uvicorn[standard]"
]
randomize = true
matrix-name-format = "{variable}-{value}"

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.11", "3.12", "3.13", "3.14"]

[tool.pytest.ini_options]
testpaths = "tests"
log_cli_level = "INFO"
filterwarnings = "ignore::DeprecationWarning"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

################################
# >>> Hatch Python Scripts <<< #
################################

[tool.hatch.envs.python]
extra-dependencies = ["pyright"]

[tool.hatch.envs.python.scripts]
type_check = ["pyright reactpy_apexcharts"]

#######################################
# >>> Hatch Documentation Scripts <<< #
#######################################

[tool.hatch.envs.docs]
template = "docs"
dependencies = [
  "mkdocs",
  "mkdocs-material",
  "mkdocstrings[python]",
  "black",  # Used by mkdocstrings for auto formatting
]

[tool.hatch.envs.docs.scripts]
serve = ["cd docs && mkdocs serve"]
build = ["cd docs && mkdocs build --strict"]

[tool.hatch.envs.javascript]
detached = true

[tool.hatch.envs.javascript.scripts]
check = ['bun install --cwd "src/js"', 'bun run --cwd "src/js" check']
fix = ['bun install --cwd "src/js"', 'bun run --cwd "src/js" format']
build-dev = [
  'bun install --cwd "src/js"',
  'bun build src/js/src/index.tsx --outdir src/reactpy_apexcharts/static --entry-naming bundle.js --target=browser --format=esm  --sourcemap=inline --minify --root=.',
]

#########################
# >>> Generic Tools <<< #
#########################

[tool.ruff]
# https://docs.astral.sh/ruff/configuration/
# https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff
line-length = 120

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md#sample-pyprojecttoml-file
typeCheckingMode = "strict"
pythonVersion = "3.11"
reportMissingTypeStubs = false
ignore = ["tmp", "tmp/**", "**/tmp/**"]
